name: Run RSpec

on:
  pull_request:
    branches: [ '*', '*/*' ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  schedule:
    - cron: '20 3 * * 2'

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  SECRET_DEVISE_JWT_SECRET_KEY: ${{ secrets.SECRET_DEVISE_JWT_SECRET_KEY }}

jobs:
  run-rspec:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec